overrides:
  -
    rules:
      no-console: warn
    files:
      - server.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/help/directives/movetop.directive.js
  -
    rules:
      no-unused-vars: warn
    files:
      - source/assets/js/modules/help/help.module.js
  -
    rules:
      security/detect-object-injection: warn
      no-console: warn
    files:
      - source/assets/js/modules/profile/controllers/import.controller.js
  -
    rules:
      security/detect-object-injection: warn
      no-extra-semi: warn
      no-undef: warn
    files:
      - source/assets/js/modules/profile/controllers/ontologies.controller.js
  -
    rules:
      security/detect-object-injection: warn
      no-extra-semi: warn
      no-unused-vars: warn
      no-useless-escape: warn
      no-unreachable: warn
    files:
      - source/assets/js/modules/profile/controllers/profile.controller.js
  -
    rules:
      security/detect-object-injection: warn
      no-undef: warn
    files:
      - source/assets/js/modules/profile/controllers/profileList.controller.js
  -
    rules:
      no-undef: warn
      no-unused-vars: warn
    files:
      - source/assets/js/modules/profile/directives/alert.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/changeColor.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/closeChooseResource.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/closeModal.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/closeWarning.directive.js
  -
    rules:
      no-undef: warn
      no-unused-vars: warn
    files:
      - source/assets/js/modules/profile/directives/datepicker.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/delete.directive.js
  -
    rules:
      no-unused-vars: warn
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/export.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/loading.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/override.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/profile.directive.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/directives/warning.directive.js
  -
    rules:
      no-extra-semi: warn
      no-unused-vars: warn
      no-console: warn
    files:
      - source/assets/js/modules/profile/resourcetemplate/controllers/resourceTemplate.controller.js
  -
    rules:
      no-unused-vars: warn
      no-console: warn
    files:
      - source/assets/js/modules/profile/resourcetemplate/propertytemplate/controllers/propertyTemplate.controller.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/services/alert.service.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/services/formHandler.service.js
  -
    rules:
      no-console: warn
    files:
      - source/assets/js/modules/profile/services/httpResponse.service.js
  -
    rules:
      no-undef: warn
      no-unused-vars: warn
    files:
      - source/assets/js/modules/profile/services/import.service.js
  -
    rules:
      no-undef: warn
      security/detect-object-injection: warn
    files:
      - source/assets/js/modules/profile/services/profileHandler.service.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/modules/profile/services/search.service.js
  -
    rules:
      no-unused-vars: warn
      no-undef: warn
    files:
      - source/assets/js/modules/profile/services/server.service.js
  -
    rules:
      no-undef: warn
      security/detect-object-injection: warn
    files:
      - source/assets/js/modules/profile/services/vocab.service.js
  -
    rules:
      no-undef: warn
    files:
      - source/assets/js/ng-app.js
