# Node.js Javascript CircleCI 2.0 configuration file
#
# Check https://hub.docker.com/r/circleci/node/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11-browsers

    working_directory: ~/sinopia_profile_editor

    steps:
      - checkout
      - run:
          name: Install latest npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: eslint
          command: npm run eslint
      - run:
          name: build with grunt
          command: npm run grunt-dev
      - run:
          name: test with jest and puppeteer
          command: npm run jest-ci
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/jest-results.xml"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          destination: jest-coverage
      - run:
          name: static analysis
          command: npm run analysis
      - store_artifacts:
          path: static-analysis
          destination: static-analysis

workflows:
  version: 2
  build:
    jobs:
      - build
