# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0

    working_directory: ~/sinopia_profile_editor

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "source/package.json" }}
      - run:
          name: Workaround for GoogleChrome/puppeteer#290
          command: 'sh .circleci/setup_puppeteer.sh'
      - run:
          name: npm-install
          command: cd source && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "source/package.json" }}
          paths:
            - ./source/node_modules
      - run:
          name: eslint
          command: cd source && npm run eslint
      - run:
          name: Run gruntjs
          command: cd source && npm run grunt-dev
      - run:
          name: test
          command: cd source && npm run jest-ci
          environment:
            JEST_JUNIT_OUTPUT: "../test-results/jest/jest-results.xml"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: source/coverage
          destination: jest-coverage
      - run:
          name: Run static analysis
          command: cd source && npm run analysis
      - store_artifacts:
          path: source/static-analysis
          destination: static-analysis

workflows:
  version: 2
  build:
    jobs:
      - build
